Bookish/Models/BooksViewModel.cs
using System.Collections.Generic;
using Bookish.Models.Database;

namespace Bookish.Models
{
    public class BooksViewModel
    {
        public IEnumerable<Book> Books { get; set; }
    }
}

Bookish/Models/Database/Book.cs
using System;

namespace Bookish.Models.Database
{
    public class Book
    {
        public int id { get; set; }
        public string Title{ get; set; }
        public int Year { get; set; }
        public string Author { get; set; }
        public string Genre { get; set; }
        
    }
}

Bookish/Models/Database/Member.cs
using System;

namespace Bookish.Models.Database
{
    public class Member
    {
        public int id { get; set; }
        public string name { get; set; }

    }
}

Bookish/Models/InventoryViewModel.cs
using System.Collections.Generic;

namespace Bookish.Models
{
    public class InventoryViewModel
    {
        public IEnumerable<InventoryModel> Inventory { get; set; }
    }
}

Bookish/Models/MembersViewModel.cs
using System;
using System.Collections.Generic;
using System.Threading.Channels;
using Bookish.Models.Database;

namespace Bookish.Models
{
    public class MembersViewModel
    {
        public IEnumerable<Member> Members { get; set; }
    }
}

Bookish/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Bookish.Models;
using Bookish.Models.Request;
using Bookish.Services;

namespace Bookish.Controllers
{   
    [Route("/books")]
    public class BooksController : Controller
    {
        private readonly IBookService _bookService;
        public BooksController(IBookService bookService)
        {
            _bookService = bookService;
        }
        
        [HttpGet("")]
        public IActionResult ViewExistingBooks()
        {
            var books = _bookService.GetAllBooks();
            var viewModel = new BooksViewModel {Books = books};
            return View(viewModel);
        }
        
        [HttpGet("create")]
        public IActionResult CreateBook()
        {
            return View();
        }
        
        [HttpPost("create")]
        public IActionResult CreateBook(CreateBookEntryModel newBook)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateBook", newBook);
            }

            _bookService.CreateBook(newBook);
            return RedirectToAction("ViewExistingBooks");

        }
        
        [HttpGet("search")]
        public IActionResult SearchBook(string searchCriteria)
        {
            var matchingBooks = _bookService.SearchBook(searchCriteria);
            var viewModel = new BooksViewModel {Books = matchingBooks};
            return View(viewModel);
        }

        [HttpPost("remove")]
        public IActionResult DeleteBook(DeleteBookEntryModel deleteBook)
        {
            _bookService.DeleteBook(deleteBook);
            return RedirectToAction("ViewExistingBooks");
        }
        
        [HttpGet("edit")]
        public IActionResult EditBook(SelectBookModel selectBook)
        {
            var book = _bookService.GetBook(selectBook);
            var viewmodel = new EditBookViewModel{Book = book }; 
            return View(viewmodel);
        } 
        
        [HttpPost("edit")]
        public IActionResult BookMember(UpdateBookModel updateBook)
        {
            _bookService.EditBook(updateBook);
            return RedirectToAction("ViewExistingBooks");
        }
        
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Bookish/Controllers/InventoryController.cs
using Bookish.Models;
using Bookish.Models.Request;
using Bookish.Services;
using Microsoft.AspNetCore.Mvc;

namespace Bookish.Controllers
{
    [Route("/inventory")]
    public class InventoryController : Controller
    {
        private readonly IInventoryService _inventoryService;

        public InventoryController(IInventoryService inventoryService)
        {
            _inventoryService = inventoryService;
        }

        [HttpGet("")]
        public IActionResult ViewLibraryInventory()
        {
            var inventoryModels = _inventoryService.GetCurrentInventory();
            var viewModel = new InventoryViewModel {Inventory = inventoryModels};
            return View(viewModel);
        }
        
        
    }
}

Bookish/Controllers/MembersController.cs
using System.Diagnostics;
using Bookish.Models;
using Bookish.Models.Request;
using Bookish.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Bookish.Controllers
{
    [Route("/members")]
    public class MembersController : Controller
    {
        private readonly IMemberService _memberService;

        public MembersController(IMemberService memberService)
        {
            _memberService = memberService;
        }
        
        [HttpGet("")]
        public IActionResult ViewAvailableMembers()
        {
            var members = _memberService.GetAllMembers();
            var viewModel = new MembersViewModel {Members = members};
            return View(viewModel);
        }

        [HttpGet("create")]
        public IActionResult CreateMember()
        {
            return View();
        }

        [HttpPost("create")]
        public IActionResult CreateMember(CreateMemberEntryModel newMember)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateMember", newMember);
            }
            _memberService.CreateMember(newMember);
            return RedirectToAction("ViewAvailableMembers");
        }
        
        [HttpGet("remove")]
        public IActionResult RemoveMember()
        {
            return View();
        }
        
        [HttpPost("remove")]
        public IActionResult RemoveMember(RemoveMemberEntryModel removeMember)
        {
            if (!ModelState.IsValid)
            {
                return View("RemoveMember", removeMember);
            }
            _memberService.RemoveMember(removeMember);
            return RedirectToAction("ViewAvailableMembers");
        }

        [HttpGet("edit")]
        public IActionResult EditMember(SelectMemberModel selectMember)
        {
            var member = _memberService.GetMember(selectMember);
            var viewmodel = new EditMemberViewModel{Member = member }; 
            return View(viewmodel);
        } 
        
        [HttpPost("edit")]
        public IActionResult EditMember(UpdateMemberModel updateMember)
        {
            _memberService.EditMember(updateMember);
            return RedirectToAction("ViewAvailableMembers");
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

Bookish/Views/Shared/_Books.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Books</h2>
<div>
        <a asp-area="" asp-controller="Books" asp-action="ViewExistingBooks">All books</a> | 
    <a asp-area="" asp-controller="Books" asp-action="CreateBook">Add a Book </a> |
    <a asp-area="" asp-controller="Books" asp-action="SearchBook">Search a Book </a> |
</div>
<hr/>
@RenderBody()

Bookish/Views/Shared/_Inventory.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Inventory</h2>
<br>
<hr/>
@RenderBody()

Bookish/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Bookish</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookish</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="ViewExistingBooks">Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="ViewAvailableMembers">Members</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="ViewLibraryInventory">Inventory</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - Bookish - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Bookish/Views/Shared/_Members.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
    <h2>Members</h2>
        <div>
            <a asp-area="" asp-controller="Members" asp-action="ViewAvailableMembers">All Members </a> | 
            <a asp-area="" asp-controller="Members" asp-action="CreateMember">Add Member </a> |
        </div>
    <hr/>

@RenderBody()